In [1]:
import torch
from torch import nn

In [2]:
inputs=torch.Tensor([[[0.2,0.1,0.3],[0.5,0.1,0.1]]])
B,S,E=inputs.size()
inputs=inputs.reshape(S,B,E)
inputs.size()

torch.Size([2, 1, 3])

In [6]:
parameter_shape=inputs.size()[-2:]
gamma=nn.Parameter(torch.ones(parameter_shape))
beta=nn.Parameter(torch.zeros(parameter_shape))


Dimensions for which we want to compute layer normalization

In [20]:
dims=[-(i+1) for i in range(len(parameter_shape))]
dims

[1, 2]

In [27]:
mean=inputs.mean(dim=[0,2],keepdim=True)
mean.size()

torch.Size([1, 1, 1])

In [28]:
mean

tensor([[[0.2167]]])

In [23]:
mean.size()

torch.Size([2, 1, 1])

In [14]:
var=((inputs-mean)**2).mean(dim=dims,keepdim=True)
std=(var+1e-5).sqrt()
std

tensor([[[0.0817]],

        [[0.1886]]])

In [15]:
y=(inputs-mean)/std
y

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]])

In [17]:
y.size()
gamma.size()

torch.Size([1, 3])

In [13]:
out=gamma*y+beta
out

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]], grad_fn=<AddBackward0>)

In [15]:
y.size()

torch.Size([2, 1, 3])

In [18]:
(gamma*y).size()

torch.Size([2, 1, 3])

In [19]:
(gamma*y).size()

torch.Size([2, 1, 3])

In [20]:
import torch
from torch import nn

class LayerNormalization(nn.Module):
    def __init__(self,parameter_shape,eps=1e-5):
        super().__init__()
        self.parameter_shape=parameter_shape
        self.eps=eps
        self.gamma=nn.Parameter(torch.ones(parameter_shape))
        self.beta=nn.Parameter(torch.zeros(parameter_shape))
    def forward(self,inputs):
        dims=[-(i+1) for i in range(len(self.parameter_shape))]
        mean=inputs.mean(dim=dims,keepdim=True)
        var=((inputs-mean)**2).mean(dim=dims,keepdim=True)
        std=(var+self.eps).sqrt()
        y=(inputs-mean)/std
        out=self.gamma*y+self.beta
        return out

ln=LayerNormalization(parameter_shape)
print(ln.forward(inputs))
        



tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]], grad_fn=<AddBackward0>)
